# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20181104_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inst',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
