# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20181104_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='id_inst',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institutions'),
        ),
        migrations.AlterField(
            model_name='inst',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='inst',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
