# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_auto_20181104_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='email',
            field=models.TextField(default='', unique=True),
        ),
    ]
